// Составы сборных ЧМ‑2026.
//
// Общая структура:
//   SQUADS_BY_TEAM_ID = {
//     MEX: {
//       formation: "4-1-4-1",
//       players: [
//         { id: "MEX-RANGEL",     name: "R. Rangel",    position: "GK",  role: "starter" },
//         { id: "MEX-GALLARDO",   name: "J. Gallardo",  position: "LB",  role: "starter" },
//         ...
//       ],
//     },
//     ...
//   }
//
// Важные моменты:
// - кто в основе / кто на замене — через поле role ("starter" | "bench");
// - по formation потом сможем раскладывать игроков по слотам на поле.

const SQUADS_BY_TEAM_ID = {
  MEX: {
    formation: "4-1-4-1",
    players: [
      // Основной состав
      { id: "MEX-RANGEL",      name: "R. Rangel",     position: "GK",  role: "starter" },
      { id: "MEX-GALLARDO",    name: "J. Gallardo",   position: "LB",  role: "starter" },
      { id: "MEX-E-LOPEZ",     name: "E. Lopez",      position: "CB",  role: "starter" },
      { id: "MEX-REYES",       name: "I. Reyes",      position: "CB",  role: "starter" },
      { id: "MEX-LEDEZMA",     name: "R. Ledezma",    position: "RB",  role: "starter" },
      { id: "MEX-LIRA",        name: "E. Lira",       position: "CDM", role: "starter" },
      { id: "MEX-E-ALVAREZ",   name: "E. Alvarez",    position: "LM",  role: "starter" },
      { id: "MEX-B-GUTIERREZ", name: "B. Gutierrez",  position: "CM",  role: "starter" },
      { id: "MEX-M-RUIZ",      name: "M. Ruiz",       position: "CM",  role: "starter" },
      { id: "MEX-R-ALVARADO",  name: "R. Alvarado",   position: "RM",  role: "starter" },
      { id: "MEX-A-GONZALEZ",  name: "A. Gonzalez",   position: "ST",  role: "starter" },

      // Запасные
      { id: "MEX-A-GUTIERREZ", name: "A. Gutierrez",  position: "RM",  role: "bench" },
      { id: "MEX-C-RODRIGUEZ", name: "C. Rodriguez",  position: "LM",  role: "bench" },
      { id: "MEX-E-SANCHEZ",   name: "E. Sanchez",    position: "CM",  role: "bench" },
      { id: "MEX-J-GARZA",     name: "J. Garza",      position: "RB",  role: "bench" },
      { id: "MEX-D-CAMPILLO",  name: "D. Campillo",   position: "CDM", role: "bench" },
      { id: "MEX-G-MARTINEZ",  name: "G. Martinez",   position: "ST",  role: "bench" },
      { id: "MEX-MALAGON",     name: "L. Malagon",    position: "GK",  role: "bench" },
      { id: "MEX-ACEVEDO",     name: "C. Acevedo",    position: "GK",  role: "bench" },
      { id: "MEX-D-GARCIA",    name: "D. Garcia",     position: "LB",  role: "bench" },
      { id: "MEX-GUZMAN",      name: "V. Guzman",     position: "CB",  role: "bench" },
    ],
  },

  RSA: {
    formation: "3-4-3",
    players: [
      // Основной состав
      { id: "RSA-WILLIAMS",   name: "R. Williams",  position: "GK",  role: "starter" },
      { id: "RSA-MBOKAZI",    name: "M. Mbokazi",   position: "CB",  role: "starter" },
      { id: "RSA-SIBISI",     name: "N. Sibisi",    position: "CB",  role: "starter" },
      { id: "RSA-NGEZANA",    name: "S. Ngezana",   position: "CB",  role: "starter" },
      { id: "RSA-KABINI",     name: "S. Kabini",    position: "LM",  role: "starter" },
      { id: "RSA-AUBAAS",     name: "B. Aubaas",    position: "CM",  role: "starter" },
      { id: "RSA-MOKOENA",    name: "T. Mokoena",   position: "CM",  role: "starter" },
      { id: "RSA-MUDAU",      name: "K. Mudau",     position: "RM",  role: "starter" },
      { id: "RSA-MOFOKENG",   name: "R. Mofokeng",  position: "LW",  role: "starter" },
      { id: "RSA-APPOLLIS",   name: "O. Appollis",  position: "RW",  role: "starter" },
      { id: "RSA-FOSTER",     name: "L. Foster",    position: "ST",  role: "starter" },

      // Запасные
      { id: "RSA-MODIBA",     name: "A. Modiba",    position: "LM",  role: "bench" },
      { id: "RSA-MAKGOPA",    name: "E. Makgopa",   position: "RW",  role: "bench" },
      { id: "RSA-MBULE",      name: "S. Mbule",     position: "LW",  role: "bench" },
      { id: "RSA-MOREMI",     name: "T. Moremi",    position: "CB",  role: "bench" },
      { id: "RSA-GOSS",       name: "R. Goss",      position: "GK",  role: "bench" },
      { id: "RSA-CHAINE",     name: "S. Chaine",    position: "GK",  role: "bench" },
      { id: "RSA-MATULUDI",   name: "T. Matuludi",  position: "RB",  role: "bench" },
      { id: "RSA-SMITH",      name: "T. Smith",     position: "RB",  role: "bench" },
      { id: "RSA-NDAMANE",    name: "K. Ndamane",   position: "CB",  role: "bench" },
      { id: "RSA-SITHOLE",    name: "S. Sithole",   position: "CM",  role: "bench" },
      { id: "RSA-MOKWANA",    name: "E. Mokwana",   position: "CM",  role: "bench" },
      { id: "RSA-NKOTA",      name: "M. Nkota",     position: "RM",  role: "bench" },
      { id: "RSA-CAMPBELL",   name: "S. Campbell",  position: "LM",  role: "bench" },
      { id: "RSA-MBATHA",     name: "T. Mbatha",    position: "CM",  role: "bench" },
    ],
  },

  KOR: {
    formation: "5-4-1",
    players: [
      // Основной состав
      { id: "KOR-SONG",     name: "B. Song",      position: "GK",  role: "starter" },
      { id: "KOR-T-LEE",    name: "T. Lee",       position: "LB",  role: "starter" },
      { id: "KOR-M-KIM",    name: "M. Kim",       position: "CB",  role: "starter" },
      { id: "KOR-JS-PARK",  name: "J. S. Park",   position: "CB",  role: "starter" },
      { id: "KOR-YM-JO",    name: "Y. M. Jo",     position: "CB",  role: "starter" },
      { id: "KOR-YW-SEOL",  name: "Y. W. Seol",   position: "RB",  role: "starter" },
      { id: "KOR-HM-SON",   name: "H. M. Son",    position: "LM",  role: "starter" },
      { id: "KOR-HK-KWON",  name: "H. K. Kwon",   position: "CM",  role: "starter" },
      { id: "KOR-CASTROP",  name: "J. Castrop",   position: "CM",  role: "starter" },
      { id: "KOR-K-LEE",    name: "K. Lee",       position: "RM",  role: "starter" },
      { id: "KOR-H-OH",     name: "H. Oh",        position: "ST",  role: "starter" },

      // Запасные
      { id: "KOR-M-SEO",    name: "M. Seo",       position: "CM",  role: "bench" },
      { id: "KOR-J-KIM",    name: "J. Kim",       position: "CM",  role: "bench" },
      { id: "KOR-HC-HWANG", name: "H. C. Hwang",  position: "LM",  role: "bench" },
      { id: "KOR-G-CHO",    name: "G. Cho",       position: "ST",  role: "bench" },
      { id: "KOR-T-KIM",    name: "T. Kim",       position: "CB",  role: "bench" },
      { id: "KOR-J-EOM",    name: "J. Eom",       position: "RM",  role: "bench" },
      { id: "KOR-H-JO",     name: "H. Jo",        position: "GK",  role: "bench" },
      { id: "KOR-S-KIM",    name: "S. Kim",       position: "GK",  role: "bench" },
      { id: "KOR-HB-LEE",   name: "H. B. Lee",    position: "CB",  role: "bench" },
      { id: "KOR-M-LEE",    name: "M. Lee",       position: "LB",  role: "bench" },
      { id: "KOR-MH-KIM",   name: "M. H. Kim",    position: "RB",  role: "bench" },
      { id: "KOR-JH-BAE",   name: "J. H. Bae",    position: "CM",  role: "bench" },
      { id: "KOR-D-WON",    name: "D. Won",       position: "CM",  role: "bench" },
      { id: "KOR-Y-MIN",    name: "Y. Min",       position: "LM",  role: "bench" },
      { id: "KOR-J-LEE",    name: "J. Lee",       position: "ST",  role: "bench" },
    ],
  },

  IRL: {
    formation: "3-4-3",
    players: [
      // Основной состав
      { id: "IRL-KELLEHER",  name: "C. Kelleher",  position: "GK",  role: "starter" },
      { id: "IRL-OSHEA",     name: "D. O'Shea",    position: "CB",  role: "starter" },
      { id: "IRL-COLLINS",   name: "N. Collins",   position: "CB",  role: "starter" },
      { id: "IRL-OBRIEN",    name: "J. O'Brien",   position: "CB",  role: "starter" },
      { id: "IRL-SCALES",    name: "L. Scales",    position: "LM",  role: "starter" },
      { id: "IRL-MOLUMBY",   name: "J. Molumby",   position: "CM",  role: "starter" },
      { id: "IRL-CULLEN",    name: "J. Cullen",    position: "CM",  role: "starter" },
      { id: "IRL-COLEMAN",   name: "S. Coleman",   position: "RM",  role: "starter" },
      { id: "IRL-AZAZ",      name: "F. Azaz",      position: "LW",  role: "starter" },
      { id: "IRL-PARROTT",   name: "T. Parrot",    position: "ST",  role: "starter" },
      { id: "IRL-OGBENE",    name: "C. Ogbene",    position: "RW",  role: "starter" },

      // Запасные
      { id: "IRL-MANNING",   name: "R. Manning",   position: "CB",  role: "bench" },
      { id: "IRL-IDAH",      name: "A. Idah",      position: "RW",  role: "bench" },
      { id: "IRL-EBOSELE",   name: "F. Ebosele",   position: "RM",  role: "bench" },
      { id: "IRL-KENNY",     name: "J. Kenny",     position: "CM",  role: "bench" },
      { id: "IRL-TAYLOR",    name: "J. Taylor",    position: "CM",  role: "bench" },
      { id: "IRL-BAZUNU",    name: "G. Bazunu",    position: "GK",  role: "bench" },
      { id: "IRL-TRAVERS",   name: "M. Travers",   position: "GK",  role: "bench" },
      { id: "IRL-DUNNE",     name: "J. Dunne",     position: "RB",  role: "bench" },
      { id: "IRL-EGAN",      name: "J. Egan",      position: "CB",  role: "bench" },
      { id: "IRL-COVENTRY",  name: "C. Coventry",  position: "CM",  role: "bench" },
      { id: "IRL-MCGRATH",   name: "J. McGrath",   position: "LM",  role: "bench" },
      { id: "IRL-JOHNSTONE", name: "M. Johnstone", position: "LM",  role: "bench" },
    ],
  },

  CAN: {
    formation: "4-4-2",
    players: [
      // Основной состав
      { id: "CAN-ST-CLAIR",  name: "D. St. Clair",     position: "GK",  role: "starter" },
      { id: "CAN-LARYEA",    name: "R. Laryea",        position: "LB",  role: "starter" },
      { id: "CAN-CORNELIUS", name: "D. Cornelius",     position: "CB",  role: "starter" },
      { id: "CAN-FOUGEROLLES", name: "L. D. Fougerolles", position: "CB", role: "starter" },
      { id: "CAN-JOHNSTONE", name: "A. Johnstone",     position: "RB",  role: "starter" },
      { id: "CAN-SHAFFELBURG", name: "J. Shaffelburg", position: "LM",  role: "starter" },
      { id: "CAN-CHOINIERE", name: "M. Choiniere",     position: "CM",  role: "starter" },
      { id: "CAN-SIGUR",     name: "N. Sigur",         position: "CM",  role: "starter" },
      { id: "CAN-BUCHANAN",  name: "T. Buchanan",      position: "RM",  role: "starter" },
      { id: "CAN-OLUWASEYI", name: "T. Oluwaseyi",     position: "ST",  role: "starter" },
      { id: "CAN-J-DAVID",   name: "J. David",         position: "ST",  role: "starter" },

      // Запасные
      { id: "CAN-JEBBISON",  name: "D. Jebbison",      position: "RM",  role: "bench" },
      { id: "CAN-SALIBA",    name: "N. Saliba",        position: "CM",  role: "bench" },
      { id: "CAN-LARIN",     name: "C. Larin",         position: "ST",  role: "bench" },
      { id: "CAN-P-DAVID",   name: "P. David",         position: "ST",  role: "bench" },
      { id: "CAN-MCGILL",    name: "T. McGill",        position: "GK",  role: "bench" },
      { id: "CAN-CREPEAU",   name: "M. Crepeau",       position: "GK",  role: "bench" },
      { id: "CAN-WATERMAN",  name: "J. Waterman",      position: "CB",  role: "bench" },
      { id: "CAN-MILLER",    name: "K. Miller",        position: "CB",  role: "bench" },
      { id: "CAN-KNIGHT",    name: "J. Knight-Lebel",  position: "CB",  role: "bench" },
      { id: "CAN-KONE",      name: "I. Kone",          position: "CM",  role: "bench" },
      { id: "CAN-BASSONG",   name: "Z. Bassong",       position: "LM",  role: "bench" },
      { id: "CAN-NELSON",    name: "J. Nelson",        position: "LM",  role: "bench" },
    ],
  },

  ITA: {
    formation: "3-5-2",
    players: [
      // Основной состав
      { id: "ITA-DONNARUMMA", name: "G. Donnaruma",    position: "GK",  role: "starter" },
      { id: "ITA-BASTONI",    name: "A. Bastoni",      position: "CB",  role: "starter" },
      { id: "ITA-MANCINI",    name: "G. Mancini",      position: "CB",  role: "starter" },
      { id: "ITA-DI-LORENZO", name: "G. Di Lorenzo",   position: "CB",  role: "starter" },
      { id: "ITA-DIMARCO",    name: "F. Dimarco",      position: "LM",  role: "starter" },
      { id: "ITA-BARELLA",    name: "N. Barella",      position: "CM",  role: "starter" },
      { id: "ITA-LOCATELLI",  name: "M. Locatelli",    position: "CM",  role: "starter" },
      { id: "ITA-FRATTESI",   name: "D. Frattesi",     position: "CM",  role: "starter" },
      { id: "ITA-POLITANO",   name: "M. Politano",     position: "RM",  role: "starter" },
      { id: "ITA-ESPOSITO",   name: "F. Esposito",     position: "ST",  role: "starter" },
      { id: "ITA-RETEGUI",    name: "M. Retegue",      position: "ST",  role: "starter" },

      // Запасные
      { id: "ITA-CRISTANTE",  name: "B. Cristante",    position: "CM",  role: "bench" },
      { id: "ITA-ZACCAGNI",   name: "M. Zaccagni",     position: "ST",  role: "bench" },
      { id: "ITA-SCAMACCA",   name: "G. Scamacca",     position: "CM",  role: "bench" },
      { id: "ITA-BUONGIORNO", name: "A. Buongiorno",   position: "CM",  role: "bench" },
      { id: "ITA-RICCI",      name: "S. Ricci",        position: "CB",  role: "bench" },
      { id: "ITA-CARNESECCHI",name: "M. Carnesecchi",  position: "GK",  role: "bench" },
      { id: "ITA-VICARIO",    name: "G. Vicario",      position: "GK",  role: "bench" },
      { id: "ITA-GABBIA",     name: "M. Gabbia",       position: "CB",  role: "bench" },
      { id: "ITA-ORSOLINI",   name: "R. Orsolini",     position: "RM",  role: "bench" },
      { id: "ITA-CAMBIASO",   name: "A. Cambiaso",     position: "LM",  role: "bench" },
      { id: "ITA-BELLANOVA",  name: "R. Bellanova",    position: "RM",  role: "bench" },
      { id: "ITA-RASPADORI",  name: "G. Raspadori",    position: "ST",  role: "bench" },
    ],
  },

  QAT: {
    formation: "4-2-3-1",
    players: [
      // Основной состав
      { id: "QAT-BARSHAM",      name: "M. A. Barsham",     position: "GK",  role: "starter" },
      { id: "QAT-BRAKE",        name: "S. A. Brake",       position: "LB",  role: "starter" },
      { id: "QAT-MENDES",       name: "L. Mendes",         position: "CB",  role: "starter" },
      { id: "QAT-AL-HUSSAIN",   name: "A. Al-Hussain",     position: "CB",  role: "starter" },
      { id: "QAT-A-A-OUI",      name: "A. A. Oui",         position: "RB",  role: "starter" },
      { id: "QAT-WAAD",         name: "M. Waad",           position: "CM",  role: "starter" },
      { id: "QAT-FATHI",        name: "A. Fathi",          position: "CM",  role: "starter" },
      { id: "QAT-H-AHMED",      name: "H. Ahmed",          position: "LM",  role: "starter" },
      { id: "QAT-ALMANAI",      name: "M. N. Almanai",     position: "CAM", role: "starter" },
      { id: "QAT-AFIF",         name: "A. Afif",           position: "RM",  role: "starter" },
      { id: "QAT-ALAAELDIN",    name: "A. Alaaeldin",      position: "ST",  role: "starter" },

      // Запасные
      { id: "QAT-SALMAN",       name: "T. Salman",         position: "LB",  role: "bench" },
      { id: "QAT-JUNIOR",       name: "E. Junior",         position: "ST",  role: "bench" },
      { id: "QAT-AYMAN",        name: "Y. Ayman",          position: "CB",  role: "bench" },
      { id: "QAT-MUNTARI",      name: "M. Muntari",        position: "RB",  role: "bench" },
      { id: "QAT-ABUNAD",       name: "M. Abunad",         position: "GK",  role: "bench" },
      { id: "QAT-ELLETHY",      name: "S. Ellethy",        position: "GK",  role: "bench" },
      { id: "QAT-LAYE",         name: "I. Laye",           position: "LB",  role: "bench" },
      { id: "QAT-HATEM",        name: "A. Hatem",          position: "CM",  role: "bench" },
      { id: "QAT-ABDULSALLAM",  name: "J. G. Abdulsallam", position: "RM",  role: "bench" },
      { id: "QAT-SABAH",        name: "K. Ali Sabah",      position: "RM",  role: "bench" },
    ],
  },

  SUI: {
    formation: "4-3-3",
    players: [
      // Основной состав
      { id: "SUI-KOBEL",      name: "G. Kobel",       position: "GK",  role: "starter" },
      { id: "SUI-RODRIGUEZ",  name: "R. Rodriguez",   position: "LB",  role: "starter" },
      { id: "SUI-AKANJI",     name: "M. Akanji",      position: "CB",  role: "starter" },
      { id: "SUI-ELVEDI",     name: "N. Elvedi",      position: "CB",  role: "starter" },
      { id: "SUI-WIDMER",     name: "S. Widmer",      position: "RB",  role: "starter" },
      { id: "SUI-SOW",        name: "D. Sow",         position: "CM",  role: "starter" },
      { id: "SUI-XHAKA",      name: "G. Xhaka",       position: "CM",  role: "starter" },
      { id: "SUI-AEBISCHER",  name: "M. Aebischer",   position: "CM",  role: "starter" },
      { id: "SUI-VARGAS",     name: "R. Vargas",      position: "LW",  role: "starter" },
      { id: "SUI-EMBOLO",     name: "B. Embolo",      position: "ST",  role: "starter" },
      { id: "SUI-MANZAMBI",   name: "J. Manzambi",    position: "RW",  role: "starter" },

      // Запасные
      { id: "SUI-RIEDER",     name: "F. Rieder",      position: "LW",  role: "bench" },
      { id: "SUI-ZEQIRI",     name: "A. Zeqiri",      position: "ST",  role: "bench" },
      { id: "SUI-SCHMIDT",    name: "I. Schmidt",     position: "RB",  role: "bench" },
      { id: "SUI-SOHM",       name: "S. Sohm",        position: "CM",  role: "bench" },
      { id: "SUI-FASSNACHT",  name: "C. Fassnacht",   position: "CM",  role: "bench" },
      { id: "SUI-MVOGO",      name: "Y. Mvogo",       position: "GK",  role: "bench" },
      { id: "SUI-KELLER",     name: "M. Keller",      position: "GK",  role: "bench" },
      { id: "SUI-MUHEIM",     name: "M. Muheim",      position: "LB",  role: "bench" },
      { id: "SUI-OMERAGIC",   name: "B. Omeragic",    position: "CB",  role: "bench" },
      { id: "SUI-AMENDA",     name: "A. Amenda",      position: "CB",  role: "bench" },
      { id: "SUI-BAJRAMI",    name: "A. Bajrami",     position: "LB",  role: "bench" },
      { id: "SUI-NDOYE",      name: "D. Ndoye",       position: "CM",  role: "bench" },
    ],
  },

  BRA: {
    formation: "4-3-3",
    players: [
      // Основной состав
      { id: "BRA-ALISSON",      name: "Alisson",       position: "GK",  role: "starter" },
      { id: "BRA-HENRIQUE",     name: "C. Henrique",   position: "LB",  role: "starter" },
      { id: "BRA-GABRIEL",      name: "Gabriel",       position: "CB",  role: "starter" },
      { id: "BRA-MARQUINHOS",   name: "Marquinhos",    position: "CB",  role: "starter" },
      { id: "BRA-WANDERSON",    name: "Wanderson",     position: "RB",  role: "starter" },
      { id: "BRA-CASEMIRO",     name: "Casemiro",      position: "CM",  role: "starter" },
      { id: "BRA-GUIMARAES",    name: "B. Guimaraes",  position: "CM",  role: "starter" },
      { id: "BRA-A-SANTOS",     name: "A. Santos",     position: "CM",  role: "starter" },
      { id: "BRA-VINICIUS",     name: "Vinicius",      position: "LW",  role: "starter" },
      { id: "BRA-RICHARLISON",  name: "Richarlison",   position: "ST",  role: "starter" },
      { id: "BRA-RAPHINHA",     name: "Raphinha",      position: "RW",  role: "starter" },

      // Запасные
      { id: "BRA-EDERSON-GK",   name: "Ederson",       position: "GK",  role: "bench" },
      { id: "BRA-BENTO",        name: "Bento",         position: "GK",  role: "bench" },
      { id: "BRA-WESLEY",       name: "Wesley",        position: "RB",  role: "bench" },
      { id: "BRA-BREMER",       name: "Bremer",        position: "CB",  role: "bench" },
      { id: "BRA-MILITAO",      name: "E. Militao",    position: "CB",  role: "bench" },
      { id: "BRA-DANILO",       name: "Danilo",        position: "CB",  role: "bench" },
      { id: "BRA-PAQUETA",      name: "L. Paqueta",    position: "CM",  role: "bench" },
      { id: "BRA-ESTEVAO",      name: "Estevao",       position: "RW",  role: "bench" },
      { id: "BRA-ENDRIK",       name: "Endrik",        position: "ST",  role: "bench" },
      { id: "BRA-CUNHA",        name: "M. Cunha",      position: "LW",  role: "bench" },
      { id: "BRA-NEYMAR",       name: "Neymar",        position: "LW",  role: "bench" },
      { id: "BRA-ANTONY",       name: "Antony",        position: "RW",  role: "bench" },
      { id: "BRA-MURILLO",      name: "Murillo",       position: "CB",  role: "bench" },
      { id: "BRA-EDERSON-CM",   name: "Ederson",       position: "CM",  role: "bench" },
      { id: "BRA-D-LUIZ",       name: "D. Luiz",       position: "CM",  role: "bench" },
    ],
  },

  MAR: {
    formation: "4-1-4-1",
    players: [
      // Основной состав
      { id: "MAR-BOUNOU",        name: "Y. Bounou",         position: "GK",  role: "starter" },
      { id: "MAR-MAZRAOUI",      name: "N. Mazraoui",       position: "LB",  role: "starter" },
      { id: "MAR-MASINA",        name: "A. Masina",         position: "CB",  role: "starter" },
      { id: "MAR-AGUERD",        name: "N. Aguerd",         position: "CB",  role: "starter" },
      { id: "MAR-HAKIMI",        name: "A. Hakimi",         position: "RB",  role: "starter" },
      { id: "MAR-EL-AYNAOUI",    name: "N. El Aynaoui",     position: "CDM", role: "starter" },
      { id: "MAR-EZZALZOULI",    name: "A. Ezzalzouli",     position: "LM",  role: "starter" },
      { id: "MAR-SAIBARI",       name: "I. Saibari",        position: "CM",  role: "starter" },
      { id: "MAR-KHANOUSS",      name: "B. E. Khannouss",   position: "CM",  role: "starter" },
      { id: "MAR-DIAZ",          name: "B. Diaz",           position: "RM",  role: "starter" },
      { id: "MAR-KAABI",         name: "A. E. Kaabi",       position: "ST",  role: "starter" },

      // Запасные
      { id: "MAR-TARHALINE",     name: "O. Tarhaline",      position: "CM",  role: "bench" },
      { id: "MAR-EN-NESYRI",     name: "Y. En-Nesyri",      position: "ST",  role: "bench" },
      { id: "MAR-EL-YAMIQ",      name: "J. El Yamiq",       position: "CB",  role: "bench" },
      { id: "MAR-SALAH-EDDINE",  name: "A. Salah-Eddine",   position: "CM",  role: "bench" },
      { id: "MAR-AKHOMACH",      name: "I. Akhomach",       position: "RM",  role: "bench" },
      { id: "MAR-IGAMANE",       name: "H. Igamane",        position: "LB",  role: "bench" },
      { id: "MAR-AL-HARRAR",     name: "M. Al Harrar",      position: "GK",  role: "bench" },
      { id: "MAR-EL-KAJOUI",     name: "M. El Kajoui",      position: "GK",  role: "bench" },
      { id: "MAR-SAISS",         name: "R. Saiss",          position: "LB",  role: "bench" },
      { id: "MAR-CHIBI",         name: "M. Chibi",          position: "RB",  role: "bench" },
      { id: "MAR-AIT-BOUBLAL",   name: "A. Ait Boublal",    position: "RB",  role: "bench" },
      { id: "MAR-BELAMMARI",     name: "Y. Belammari",      position: "LB",  role: "bench" },
      { id: "MAR-TALBI",         name: "C. Talbi",          position: "LM",  role: "bench" },
      { id: "MAR-AMRABAT",       name: "S. Amrabat",        position: "CM",  role: "bench" },
      { id: "MAR-RAHIMI",        name: "S. Rahimi",         position: "ST",  role: "bench" },
    ],
  },

  HAI: {
    formation: "4-2-3-1",
    players: [
      // Основной состав
      { id: "HAI-PLACIDE",       name: "J. Placide",        position: "GK",  role: "starter" },
      { id: "HAI-LACROIX",       name: "D. Lacroix",        position: "LB",  role: "starter" },
      { id: "HAI-DELCROIX",      name: "H. Delcroix",       position: "CB",  role: "starter" },
      { id: "HAI-ADE",           name: "R. Ade",            position: "CB",  role: "starter" },
      { id: "HAI-ARCUS",         name: "C. Arcus",          position: "RB",  role: "starter" },
      { id: "HAI-PIERRE",        name: "L. Pierre",         position: "CM",  role: "starter" },
      { id: "HAI-BELLEGARDE",    name: "J. R. Bellegarde",  position: "CM",  role: "starter" },
      { id: "HAI-PROVIDENCE",    name: "R. Providence",     position: "LM",  role: "starter" },
      { id: "HAI-CASIMIR",       name: "J. Casimir",        position: "CAM", role: "starter" },
      { id: "HAI-DEEDSON",       name: "L. D. Deedson",     position: "RM",  role: "starter" },
      { id: "HAI-PIERROT",       name: "F. Pierrot",        position: "ST",  role: "starter" },

      // Запасные
      { id: "HAI-NAZON",         name: "D. Nazon",          position: "ST",  role: "bench" },
      { id: "HAI-EXPERIENCE",    name: "M. Experience",     position: "RM",  role: "bench" },
      { id: "HAI-LAMBESE",       name: "S. Lambese",        position: "RB",  role: "bench" },
      { id: "HAI-SAINTE",        name: "C. Sainte",         position: "LM",  role: "bench" },
      { id: "HAI-DUVERGER",      name: "J. Duverger",       position: "GK",  role: "bench" },
      { id: "HAI-A-PIERRE",      name: "A. Pierre",         position: "GK",  role: "bench" },
      { id: "HAI-METUSALA",      name: "G. Metusala",       position: "CB",  role: "bench" },
      { id: "HAI-THERMONCY",     name: "K. Thermoncy",      position: "CB",  role: "bench" },
      { id: "HAI-ATTYS",         name: "C. Attys",          position: "RM",  role: "bench" },
      { id: "HAI-JUNIOR",        name: "D. Junior",         position: "ST",  role: "bench" },
      { id: "HAI-PACIUS",        name: "W. Pacius",         position: "ST",  role: "bench" },
    ],
  },

  SCO: {
    formation: "4-1-4-1",
    players: [
      // Основной состав
      { id: "SCO-GORDON",        name: "C. Gordon",         position: "GK",  role: "starter" },
      { id: "SCO-ROBERTSON",     name: "A. Robertson",      position: "LB",  role: "starter" },
      { id: "SCO-MCKENNA",       name: "S. McKenna",        position: "CB",  role: "starter" },
      { id: "SCO-HANLEY",        name: "G. Hanley",         position: "CB",  role: "starter" },
      { id: "SCO-HICKEY",        name: "A. Hickey",         position: "RB",  role: "starter" },
      { id: "SCO-FERGUSON",      name: "L. Ferguson",       position: "CDM", role: "starter" },
      { id: "SCO-MCGINN",        name: "J. McGinn",         position: "LM",  role: "starter" },
      { id: "SCO-MCTOMINAY",     name: "S. McTominay",      position: "CM",  role: "starter" },
      { id: "SCO-CHRISTIE",      name: "R. Christie",       position: "CM",  role: "starter" },
      { id: "SCO-DOAK",          name: "B. Doak",           position: "RM",  role: "starter" },
      { id: "SCO-DYKES",         name: "L. Dykes",          position: "ST",  role: "starter" },

      // Запасные
      { id: "SCO-MCLEAN",        name: "K. McLean",         position: "RM",  role: "bench" },
      { id: "SCO-ADAMS",         name: "C. Adams",          position: "ST",  role: "bench" },
      { id: "SCO-SHANKLAND",     name: "L. Shankland",      position: "CM",  role: "bench" },
      { id: "SCO-TIERNEY",       name: "K. Tierney",        position: "RB",  role: "bench" },
      { id: "SCO-KELLY",         name: "L. Kelly",          position: "GK",  role: "bench" },
      { id: "SCO-BAIN",          name: "S. Bain",           position: "GK",  role: "bench" },
      { id: "SCO-HENDRY",        name: "J. Hendry",         position: "CB",  role: "bench" },
      { id: "SCO-RALSTON",       name: "A. Ralston",        position: "RB",  role: "bench" },
      { id: "SCO-IRVING",        name: "A. Irving",         position: "CM",  role: "bench" },
      { id: "SCO-BARRON",        name: "C. Barron",         position: "CM",  role: "bench" },
      { id: "SCO-HIRST",         name: "G. Hirst",          position: "ST",  role: "bench" },
    ],
  },

  USA: {
    formation: "3-4-3",
    players: [
      // Основной состав
      { id: "USA-FREESE",      name: "M. Freese",      position: "GK",  role: "starter" },
      { id: "USA-TRUSTY",      name: "A. Trusty",      position: "CB",  role: "starter" },
      { id: "USA-MCKENZIE",    name: "M. McKenzie",    position: "CB",  role: "starter" },
      { id: "USA-FREEMAN",     name: "A. Freeman",     position: "CB",  role: "starter" },
      { id: "USA-TOLKIN",      name: "J. Tolkin",      position: "LM",  role: "starter" },
      { id: "USA-BERHALTER",   name: "S. Berhalter",   position: "CM",  role: "starter" },
      { id: "USA-MORRIS",      name: "A. Morris",      position: "CM",  role: "starter" },
      { id: "USA-DEST",        name: "S. Dest",        position: "RM",  role: "starter" },
      { id: "USA-LUNA",        name: "D. Luna",        position: "LW",  role: "starter" },
      { id: "USA-WRIGHT",      name: "H. Wright",      position: "ST",  role: "starter" },
      { id: "USA-TILLMAN",     name: "T. Tillman",     position: "RW",  role: "starter" },

      // Запасные
      { id: "USA-BALOGUN",     name: "F. Balogun",     position: "ST",  role: "bench" },
      { id: "USA-TESSMANN",    name: "T. Tessmann",    position: "RM",  role: "bench" },
      { id: "USA-REYNA",       name: "G. Reyna",       position: "LW",  role: "bench" },
      { id: "USA-ARFSTEN",     name: "M. Arfsten",     position: "LM",  role: "bench" },
      { id: "USA-AARONSON",    name: "B. Aaronson",    position: "RW",  role: "bench" },
      { id: "USA-ROLDAN",      name: "C. Roldan",      position: "CM",  role: "bench" },
      { id: "USA-CELENTANO",   name: "R. Celentano",   position: "GK",  role: "bench" },
      { id: "USA-SCHULTE",     name: "P. Schulte",     position: "GK",  role: "bench" },
      { id: "USA-KLINSMANN",   name: "J. Klinsmann",   position: "GK",  role: "bench" },
      { id: "USA-PULISIC",     name: "C. Pulisic",     position: "RW",  role: "bench" },
      { id: "USA-SCALLY",      name: "J. Scally",      position: "CB",  role: "bench" },
      { id: "USA-ROBINSON",    name: "M. Robinson",    position: "CB",  role: "bench" },
      { id: "USA-REAM",        name: "T. Ream",        position: "CB",  role: "bench" },
      { id: "USA-PEPI",        name: "R. Pepi",        position: "ST",  role: "bench" },
    ],
  },

  PAR: {
    formation: "4-2-3-1",
    players: [
      // Основной состав
      { id: "PAR-GILL",        name: "O. Gill",        position: "GK",  role: "starter" },
      { id: "PAR-SANDEZ",      name: "A. Sandez",      position: "LB",  role: "starter" },
      { id: "PAR-DUARTE",      name: "A. Duarte",      position: "CB",  role: "starter" },
      { id: "PAR-VELAZQUEZ",   name: "G. Velazquez",   position: "CB",  role: "starter" },
      { id: "PAR-BENITEZ",     name: "A. Benitez",     position: "RB",  role: "starter" },
      { id: "PAR-GALARZA",     name: "M. Galarza",     position: "CDM", role: "starter" },
      { id: "PAR-OJEDA",       name: "B. Ojeda",       position: "CDM", role: "starter" },
      { id: "PAR-ALMIRON",     name: "M. Almiron",     position: "LM",  role: "starter" },
      { id: "PAR-D-GOMEZ",     name: "D. Gomez",       position: "CAM", role: "starter" },
      { id: "PAR-SOSA",        name: "R. Sosa",        position: "RM",  role: "starter" },
      { id: "PAR-SANABRIA",    name: "A. Sanabria",    position: "ST",  role: "starter" },

      // Запасные
      { id: "PAR-BOBADILLA",   name: "D. Bobadilla",   position: "CAM", role: "bench" },
      { id: "PAR-ENCISO",      name: "J. Enciso",      position: "LM",  role: "bench" },
      { id: "PAR-GONZALEZ",    name: "D. Gonzalez",    position: "RM",  role: "bench" },
      { id: "PAR-ARCE",        name: "A. Arce",        position: "ST",  role: "bench" },
      { id: "PAR-ALONSO",      name: "J. Alonso",      position: "CDM", role: "bench" },
      { id: "PAR-ROMERO",      name: "L. Romero",      position: "CDM", role: "bench" },
      { id: "PAR-FERNANDEZ",   name: "G. Fernandez",   position: "GK",  role: "bench" },
      { id: "PAR-PEREZ",       name: "A. Perez",       position: "GK",  role: "bench" },
      { id: "PAR-CACERES",     name: "J. Caceres",     position: "RB",  role: "bench" },
      { id: "PAR-RIVEROS",     name: "B. Riveros",     position: "LB",  role: "bench" },
      { id: "PAR-G-GOMEZ",     name: "G. Gomez",       position: "CB",  role: "bench" },
      { id: "PAR-LEON",        name: "D. Leon",        position: "LB",  role: "bench" },
      { id: "PAR-A-ROMERO",    name: "A. Romero",      position: "RM",  role: "bench" },
      { id: "PAR-MARTINEZ",    name: "R. Martinez",    position: "ST",  role: "bench" },
    ],
  },

  AUS: {
    formation: "5-4-1",
    players: [
      // Основной состав
      { id: "AUS-IZZO",        name: "P. Izzo",            position: "GK",  role: "starter" },
      { id: "AUS-ROWLES",      name: "K. Rowles",          position: "LB",  role: "starter" },
      { id: "AUS-BURGESS",     name: "C. Burgess",         position: "CB",  role: "starter" },
      { id: "AUS-DEGENEK",     name: "M. Degenek",         position: "CB",  role: "starter" },
      { id: "AUS-TREWIN",      name: "K. Trewin",          position: "CB",  role: "starter" },
      { id: "AUS-MILLER",      name: "L. Miller",          position: "RB",  role: "starter" },
      { id: "AUS-MCGREE",      name: "R. McGree",          position: "LM",  role: "starter" },
      { id: "AUS-ONEILL",      name: "A. O'Neill",         position: "CM",  role: "starter" },
      { id: "AUS-IRVINE",      name: "J. Irvine",          position: "CM",  role: "starter" },
      { id: "AUS-METCALFE",    name: "C. Metcalfe",        position: "RM",  role: "starter" },
      { id: "AUS-M-TOURE",     name: "M. Toure",           position: "ST",  role: "starter" },

      // Запасные
      { id: "AUS-ELDER",       name: "C. Elder",           position: "LB",  role: "bench" },
      { id: "AUS-BALARD",      name: "M. Balard",          position: "CM",  role: "bench" },
      { id: "AUS-OKON",        name: "P. Okon-Engstler",   position: "CM",  role: "bench" },
      { id: "AUS-BOYLE",       name: "M. Boyle",           position: "RM",  role: "bench" },
      { id: "AUS-IRANKUNDA",   name: "N. Irankunda",       position: "LM",  role: "bench" },
      { id: "AUS-H-TOURE",     name: "H. Toure",           position: "ST",  role: "bench" },
      { id: "AUS-RYAN",        name: "M. Ryan",            position: "GK",  role: "bench" },
      { id: "AUS-BEACH",       name: "P. Beach",           position: "GK",  role: "bench" },
      { id: "AUS-OVERY",       name: "J. Overy",           position: "CB",  role: "bench" },
      { id: "AUS-IREDALE",     name: "J. Iredale",         position: "LB",  role: "bench" },
      { id: "AUS-DEVLIN",      name: "C. Devlin",          position: "CM",  role: "bench" },
      { id: "AUS-GOODWIN",     name: "C. Goodwin",         position: "LM",  role: "bench" },
    ],
  },

  TUR: {
    formation: "5-4-1",
    players: [
      // Основной состав
      { id: "TUR-BAYINDIR",    name: "A. Bayindir",     position: "GK",  role: "starter" },
      { id: "TUR-KADIOGLU",    name: "F. Kadioglu",     position: "LB",  role: "starter" },
      { id: "TUR-SOYUNCU",     name: "C. Soyuncu",      position: "CB",  role: "starter" },
      { id: "TUR-DEMIRAL",     name: "M. Demiral",      position: "CB",  role: "starter" },
      { id: "TUR-AKAYDIN",     name: "S. Akaydin",      position: "CB",  role: "starter" },
      { id: "TUR-CELIK",       name: "Z. Celik",        position: "RB",  role: "starter" },
      { id: "TUR-YELDIZ",      name: "K. Yeldiz",       position: "LM",  role: "starter" },
      { id: "TUR-KOKCU",       name: "O. Kokcu",        position: "CM",  role: "starter" },
      { id: "TUR-OZCAN",       name: "S. Ozcan",        position: "CM",  role: "starter" },
      { id: "TUR-GULER",       name: "A. Guler",        position: "RM",  role: "starter" },
      { id: "TUR-GUL",         name: "D. Gul",          position: "ST",  role: "starter" },

      // Запасные
      { id: "TUR-MULDUR",      name: "M. Muldur",       position: "ST",  role: "bench" },
      { id: "TUR-SARI",        name: "Y. Sari",         position: "RM",  role: "bench" },
      { id: "TUR-ESKIHELLAC",  name: "M. Eskihellac",   position: "LB",  role: "bench" },
      { id: "TUR-KARAZOR",     name: "A. Karazor",      position: "CM",  role: "bench" },
      { id: "TUR-AKCICEK",     name: "Y. Akcicek",      position: "CB",  role: "bench" },
      { id: "TUR-GUNOK",       name: "M. Gunok",        position: "GK",  role: "bench" },
      { id: "TUR-CAKIR",       name: "U. Cakir",        position: "GK",  role: "bench" },
      { id: "TUR-VURAL",       name: "I. Vural",        position: "LM",  role: "bench" },
      { id: "TUR-KAHVECI",     name: "I. C. Kahveci",   position: "RM",  role: "bench" },
      { id: "TUR-KUTUCU",      name: "A. Kutucu",       position: "LM",  role: "bench" },
      { id: "TUR-AYDIN",       name: "O. Aydin",        position: "CM",  role: "bench" },
      { id: "TUR-YILMAZ",      name: "B. A. Yilmaz",    position: "LM",  role: "bench" },
    ],
  },

  GER: {
    formation: "4-2-3-1",
    players: [
      // Основной состав
      { id: "GER-BAUMANN",      name: "O. Baumann",        position: "GK",  role: "starter" },
      { id: "GER-RAUM",         name: "D. Raum",           position: "LB",  role: "starter" },
      { id: "GER-SCHLOTTERBECK",name: "N. Schlotterbeck",  position: "CB",  role: "starter" },
      { id: "GER-TAH",          name: "J. Tah",            position: "CB",  role: "starter" },
      { id: "GER-KIMMICH",      name: "J. Kimmich",        position: "RB",  role: "starter" },
      { id: "GER-PAVLOVIC",     name: "A. Pavlovic",       position: "CDM", role: "starter" },
      { id: "GER-GORETZKA",     name: "L. Goretzka",       position: "CDM", role: "starter" },
      { id: "GER-WIRTZ",        name: "F. Wirtz",          position: "LM",  role: "starter" },
      { id: "GER-GNABRY",       name: "S. Gnabry",         position: "CAM", role: "starter" },
      { id: "GER-SANE",         name: "L. Sane",           position: "RM",  role: "starter" },
      { id: "GER-WOLTEMADE",    name: "N. Woltemade",      position: "ST",  role: "starter" },

      // Запасные
      { id: "GER-NMECHA",       name: "F. Nmecha",         position: "CDM", role: "bench" },
      { id: "GER-BAKU",         name: "R. Baku",           position: "RB",  role: "bench" },
      { id: "GER-THIAW",        name: "M. Thiaw",          position: "CB",  role: "bench" },
      { id: "GER-BROWN",        name: "N. Brown",          position: "LB",  role: "bench" },
      { id: "GER-OUEDRAOGO",    name: "A. Ouedraogo",      position: "LM",  role: "bench" },
      { id: "GER-NUBEL",        name: "A. Nubel",          position: "GK",  role: "bench" },
      { id: "GER-DAHMEN",       name: "F. Dahmen",         position: "GK",  role: "bench" },
      { id: "GER-ANTON",        name: "W. Anton",          position: "CB",  role: "bench" },
      { id: "GER-LEWELING",     name: "J. Leweling",       position: "RM",  role: "bench" },
      { id: "GER-SCHADE",       name: "K. Schade",         position: "CDM", role: "bench" },
      { id: "GER-ADEYEMI",      name: "K. Adeyemi",        position: "ST",  role: "bench" },
      { id: "GER-BURKARDT",     name: "J. Burkardt",       position: "CAM", role: "bench" },
    ],
  },

  CUW: {
    formation: "4-3-3",
    players: [
      // Основной состав
      { id: "CUW-ROOM",         name: "E. Room",           position: "GK",  role: "starter" },
      { id: "CUW-FLORANUS",     name: "S. Floranus",       position: "LB",  role: "starter" },
      { id: "CUW-OBISPO",       name: "A. Obispo",         position: "CB",  role: "starter" },
      { id: "CUW-EIJMA",        name: "R. v. Eijma",       position: "CB",  role: "starter" },
      { id: "CUW-SAMBO",        name: "S. Sambo",          position: "RB",  role: "starter" },
      { id: "CUW-J-BACUNA",     name: "J. Bacuna",         position: "CM",  role: "starter" },
      { id: "CUW-COMENENCIA",   name: "L. Comenencia",     position: "CM",  role: "starter" },
      { id: "CUW-L-BACUNA",     name: "L. Bacuna",         position: "CM",  role: "starter" },
      { id: "CUW-GORRE",        name: "K. Gorre",          position: "LW",  role: "starter" },
      { id: "CUW-LOCADIA",      name: "J. Locadia",        position: "ST",  role: "starter" },
      { id: "CUW-HANSEN",       name: "S. Hansen",         position: "RW",  role: "starter" },

      // Запасные
      { id: "CUW-ANTONISSE",    name: "J. Antonisse",      position: "LW",  role: "bench" },
      { id: "CUW-GAARI",        name: "J. Gaari",          position: "RW",  role: "bench" },
      { id: "CUW-PAULINA",      name: "J. Paulina",        position: "ST",  role: "bench" },
      { id: "CUW-BODAK",        name: "T. Bodak",          position: "GK",  role: "bench" },
      { id: "CUW-DOORNBUSCH",   name: "T. Doornbusch",     position: "GK",  role: "bench" },
      { id: "CUW-FONVILLE",     name: "D. Fonville",       position: "LB",  role: "bench" },
      { id: "CUW-MARTHA",       name: "A. Martha",         position: "CB",  role: "bench" },
      { id: "CUW-BRENET",       name: "J. Brenet",         position: "RB",  role: "bench" },
      { id: "CUW-ROEMERATOE",   name: "G. Roemeratoe",     position: "CM",  role: "bench" },
      { id: "CUW-FELIDA",       name: "K. Felida",         position: "CM",  role: "bench" },
      { id: "CUW-MARGARITHA",   name: "J. Margaritha",     position: "CM",  role: "bench" },
      { id: "CUW-NOSLIN",       name: "T. Noslin",         position: "CM",  role: "bench" },
    ],
  },

  CIV: {
    formation: "4-3-3",
    players: [
      // Основной состав
      { id: "CIV-FOFANA",       name: "Y. Fofana",         position: "GK",  role: "starter" },
      { id: "CIV-CONAN",        name: "G. Conan",          position: "LB",  role: "starter" },
      { id: "CIV-NDICKA",       name: "E. Ndicka",         position: "CB",  role: "starter" },
      { id: "CIV-KOSSOUNOU",    name: "O. Kossounou",      position: "CB",  role: "starter" },
      { id: "CIV-DOUE",         name: "G. Doue",           position: "RB",  role: "starter" },
      { id: "CIV-OUALI",        name: "C. I. Oulai",       position: "CM",  role: "starter" },
      { id: "CIV-SANGARE",      name: "L. Sangare",        position: "CM",  role: "starter" },
      { id: "CIV-KESSIE",       name: "F. Kessie",         position: "CM",  role: "starter" },
      { id: "CIV-DIOMANDE",     name: "Y. Diomande",       position: "LW",  role: "starter" },
      { id: "CIV-GUESSAND",     name: "E. Guessand",       position: "ST",  role: "starter" },
      { id: "CIV-DIALLO",       name: "A. Diallo",         position: "RW",  role: "starter" },

      // Запасные
      { id: "CIV-KRASSO",       name: "J. P. Krasso",      position: "CM",  role: "bench" },
      { id: "CIV-BAYO",         name: "V. Bayo",           position: "ST",  role: "bench" },
      { id: "CIV-TOURE",        name: "B. Toure",          position: "LW",  role: "bench" },
      { id: "CIV-S-FOFANA",     name: "S. Fofana",         position: "CM",  role: "bench" },
      { id: "CIV-KONE",         name: "M. Kone",           position: "GK",  role: "bench" },
      { id: "CIV-LAFONT",       name: "A. Lafont",         position: "GK",  role: "bench" },
      { id: "CIV-O-DIOMANDE",   name: "O. Diomande",       position: "RB",  role: "bench" },
      { id: "CIV-OPERI",        name: "C. Operi",          position: "LB",  role: "bench" },
      { id: "CIV-ZOHOURI",      name: "A. J. Zohouri",     position: "CB",  role: "bench" },
      { id: "CIV-BOLY",         name: "W. Boly",           position: "CB",  role: "bench" },
      { id: "CIV-GBAMIN",       name: "J. P. Gbamin",      position: "CB",  role: "bench" },
      { id: "CIV-AGBADOU",      name: "E. Agbadou",        position: "CB",  role: "bench" },
      { id: "CIV-ZAHA",         name: "W. Zaha",           position: "LW",  role: "bench" },
      { id: "CIV-SERI",         name: "J. M. Seri",        position: "CM",  role: "bench" },
      { id: "CIV-DIAKITE",      name: "O. Diakite",        position: "ST",  role: "bench" },
    ],
  },

  ECU: {
    formation: "4-4-2",
    players: [
      // Основной состав
      { id: "ECU-GALINDEZ",     name: "H. Galindez",       position: "GK",  role: "starter" },
      { id: "ECU-HINCAPIE",     name: "P. Hincapie",       position: "LB",  role: "starter" },
      { id: "ECU-PACHO",        name: "W. Pacho",          position: "CB",  role: "starter" },
      { id: "ECU-ORDONEZ",      name: "J. Ordonez",        position: "CB",  role: "starter" },
      { id: "ECU-FRANCO",       name: "A. Franco",         position: "RB",  role: "starter" },
      { id: "ECU-ANGULO",       name: "N. Angulo",         position: "LM",  role: "starter" },
      { id: "ECU-VITE",         name: "P. Vite",           position: "CM",  role: "starter" },
      { id: "ECU-CAICEDO",      name: "M. Caicedo",        position: "CM",  role: "starter" },
      { id: "ECU-YEBOAH",       name: "J. Yeboah",         position: "RM",  role: "starter" },
      { id: "ECU-CAMPANA",      name: "L. Campana",        position: "ST",  role: "starter" },
      { id: "ECU-PLATA",        name: "G. Plata",          position: "ST",  role: "starter" },

      // Запасные
      { id: "ECU-D-CASTILLO",   name: "D. Castillo",       position: "RB",  role: "bench" },
      { id: "ECU-ALCIVAR",      name: "J. Alcivar",        position: "CM",  role: "bench" },
      { id: "ECU-MERCADO-RM",   name: "J. Mercado",        position: "RM",  role: "bench" },
      { id: "ECU-MINDA",        name: "A. Minda",          position: "LM",  role: "bench" },
      { id: "ECU-M-RAMIREZ",    name: "M. Ramirez",        position: "GK",  role: "bench" },
      { id: "ECU-LOOR",         name: "C. Loor",           position: "GK",  role: "bench" },
      { id: "ECU-C-RAMIREZ",    name: "C. Ramirez",        position: "LB",  role: "bench" },
      { id: "ECU-REALPE",       name: "L. Realpe",         position: "LB",  role: "bench" },
      { id: "ECU-TORRES",       name: "F. Torres",         position: "CB",  role: "bench" },
      { id: "ECU-MEDINA",       name: "Y. Medina",         position: "LB",  role: "bench" },
      { id: "ECU-PRECIADO",     name: "A. Preciado",       position: "RM",  role: "bench" },
      { id: "ECU-PAEZ",         name: "K. Paez",           position: "RM",  role: "bench" },
      { id: "ECU-MERCADO-CM",   name: "P. Mercado",        position: "CM",  role: "bench" },
      { id: "ECU-RODRIGUEZ",    name: "K. Rodriguez",      position: "ST",  role: "bench" },
      { id: "ECU-AREVALO",      name: "J. Arevalo",        position: "ST",  role: "bench" },
    ],
  },

  NED: {
    formation: "4-3-3",
    players: [
      // Основной состав
      { id: "NED-VERBRUGGEN",   name: "B. Verbrugen",      position: "GK",  role: "starter" },
      { id: "NED-AKE",          name: "N. Ake",            position: "LB",  role: "starter" },
      { id: "NED-VAN-DIJK",     name: "V. van Dijk",       position: "CB",  role: "starter" },
      { id: "NED-DE-LIGT",      name: "M. de Ligt",        position: "CB",  role: "starter" },
      { id: "NED-TIMBER",       name: "J. Timber",         position: "RB",  role: "starter" },
      { id: "NED-SIMONS",       name: "X. Simons",         position: "CM",  role: "starter" },
      { id: "NED-DE-JONG",      name: "F. de Jong",        position: "CM",  role: "starter" },
      { id: "NED-REIJNDERS",    name: "T. Reijnders",      position: "CM",  role: "starter" },
      { id: "NED-GAKPO",        name: "C. Gakpo",          position: "LW",  role: "starter" },
      { id: "NED-DEPAY",        name: "M. Depay",          position: "ST",  role: "starter" },
      { id: "NED-MALEN",        name: "D. Malen",          position: "RW",  role: "starter" },

      // Запасные
      { id: "NED-EMEGHA",       name: "E. Emegha",         position: "ST",  role: "bench" },
      { id: "NED-GEERTRUIDA",   name: "L. Geertruida",     position: "RB",  role: "bench" },
      { id: "NED-Q-TIMBER",     name: "Q. Timber",         position: "CM",  role: "bench" },
      { id: "NED-VALENTE",      name: "L. Valente",        position: "CM",  role: "bench" },
      { id: "NED-LANG",         name: "N. Lang",           position: "LW",  role: "bench" },
      { id: "NED-FLEKKEN",      name: "M. Flekken",        position: "GK",  role: "bench" },
      { id: "NED-ROEFS",        name: "R. Roefs",          position: "GK",  role: "bench" },
      { id: "NED-VAN-DE-VEN",   name: "M. van de Ven",     position: "CB",  role: "bench" },
      { id: "NED-SCHOUTEN",     name: "J. Schouten",       position: "CM",  role: "bench" },
      { id: "NED-GRAVENBERCH",  name: "R. Gravenberch",    position: "CM",  role: "bench" },
    ],
  },

  JPN: {
    formation: "3-4-3",
    players: [
      // Основной состав
      { id: "JPN-HAYAKAWA",     name: "T. Hayakawa",       position: "GK",  role: "starter" },
      { id: "JPN-SEKO",         name: "A. Seko",           position: "CB",  role: "starter" },
      { id: "JPN-TANIGUCHI",    name: "S. Taniguchi",      position: "CB",  role: "starter" },
      { id: "JPN-ITAKURA",      name: "K. Itakura",        position: "CB",  role: "starter" },
      { id: "JPN-MAEDA",        name: "D. Maeda",          position: "LM",  role: "starter" },
      { id: "JPN-KAMADA",       name: "D. Kamada",         position: "CM",  role: "starter" },
      { id: "JPN-ENDO",         name: "W. Endo",           position: "CM",  role: "starter" },
      { id: "JPN-SUGUWARA",     name: "Y. Suguwara",       position: "RM",  role: "starter" },
      { id: "JPN-MINAMINO",     name: "T. Minamino",       position: "LW",  role: "starter" },
      { id: "JPN-OGAWA",        name: "K. Ogawa",          position: "ST",  role: "starter" },
      { id: "JPN-KUBA",         name: "T. Kuba",           position: "RW",  role: "starter" },

      // Запасные
      { id: "JPN-DOAN",         name: "R. Doan",           position: "RM",  role: "bench" },
      { id: "JPN-NAKAMURA",     name: "K. Nakamura",       position: "LW",  role: "bench" },
      { id: "JPN-UEDA",         name: "A. Ueda",           position: "ST",  role: "bench" },
      { id: "JPN-MACHINO",      name: "S. Machino",        position: "RW",  role: "bench" },
      { id: "JPN-FUJITA",       name: "J. C. Fujita",      position: "CM",  role: "bench" },
      { id: "JPN-GOTO",         name: "K. Goto",           position: "LM",  role: "bench" },
      { id: "JPN-KOKUBO",       name: "L. Kokubo",         position: "GK",  role: "bench" },
      { id: "JPN-NOZAWA",       name: "T. B. Nozawa",      position: "GK",  role: "bench" },
      { id: "JPN-WATANABE",     name: "T. Watanabe",       position: "CB",  role: "bench" },
      { id: "JPN-ANDO",         name: "T. Ando",           position: "CB",  role: "bench" },
      { id: "JPN-SUZUKI",       name: "J. Suzuki",         position: "CB",  role: "bench" },
      { id: "JPN-SANO",         name: "K. Sano",           position: "CM",  role: "bench" },
      { id: "JPN-TANAKA",       name: "A. Tanaka",         position: "CM",  role: "bench" },
      { id: "JPN-KITANO",       name: "S. Kitano",         position: "CM",  role: "bench" },
      { id: "JPN-SATO",         name: "R. Sato",           position: "LM",  role: "bench" },
    ],
  },

  SWE: {
    formation: "4-4-2",
    players: [
      // Основной состав
      { id: "SWE-ZETTERSTROM",  name: "W. Zetterstom",     position: "GK",  role: "starter" },
      { id: "SWE-SVENSSON",     name: "D. Svensson",       position: "LB",  role: "starter" },
      { id: "SWE-LINDELOF",     name: "V. Lindelof",       position: "CB",  role: "starter" },
      { id: "SWE-STARFELT",     name: "C. Starfelt",       position: "CB",  role: "starter" },
      { id: "SWE-KRAFTH",       name: "E. Krafth",         position: "RB",  role: "starter" },
      { id: "SWE-SEMA",         name: "K. Sema",           position: "LM",  role: "starter" },
      { id: "SWE-SVANBERG",     name: "M. Svanberg",       position: "CM",  role: "starter" },
      { id: "SWE-ZENELI",       name: "B. Zeneli",         position: "CM",  role: "starter" },
      { id: "SWE-LUNDGREN",     name: "G. Lundgren",       position: "RM",  role: "starter" },
      { id: "SWE-GYOKERES",     name: "V. Gyokeres",       position: "ST",  role: "starter" },
      { id: "SWE-ISAK",         name: "A. Isak",           position: "ST",  role: "starter" },

      // Запасные
      { id: "SWE-FORSBERG",     name: "E. Forsberg",       position: "LM",  role: "bench" },
      { id: "SWE-GUDMUNDSON",   name: "G. Gudmundson",     position: "RB",  role: "bench" },
      { id: "SWE-JOHANSSON",    name: "H. Johansson",      position: "CM",  role: "bench" },
      { id: "SWE-BERNHARDSSON", name: "A. Bernhardsson",   position: "ST",  role: "bench" },
      { id: "SWE-LAGERBIELKE",  name: "G. Lagerbielke",    position: "CB",  role: "bench" },
      { id: "SWE-TORNQVIST",    name: "N. Tornqvist",      position: "GK",  role: "bench" },
      { id: "SWE-NORDFELDT",    name: "K. Nordfeldt",      position: "GK",  role: "bench" },
      { id: "SWE-HIEN",         name: "I. Hien",           position: "CB",  role: "bench" },
      { id: "SWE-KARLSTROM",    name: "J. Karlstrom",      position: "CM",  role: "bench" },
      { id: "SWE-AYARI",        name: "Y. Ayari",          position: "CM",  role: "bench" },
      { id: "SWE-NYGREN",       name: "B. Nygren",         position: "ST",  role: "bench" },
      { id: "SWE-LARSSON",      name: "H. Larsson",        position: "CM",  role: "bench" },
      { id: "SWE-BERGVALL",     name: "L. Bergvall",       position: "CM",  role: "bench" },
      { id: "SWE-BARDGHJI",     name: "R. Bardghji",       position: "RM",  role: "bench" },
      { id: "SWE-LIDBERG",      name: "L. Lidberg",        position: "ST",  role: "bench" },
    ],
  },

  TUN: {
    formation: "4-2-3-1",
    players: [
      // Основной состав
      { id: "TUN-DAHMEN",       name: "A. Dahmen",         position: "GK",  role: "starter" },
      { id: "TUN-ABDI",         name: "A. Abdi",           position: "LB",  role: "starter" },
      { id: "TUN-TALBI",        name: "M. Talbi",          position: "CB",  role: "starter" },
      { id: "TUN-BRONN",        name: "D. Bronn",          position: "CB",  role: "starter" },
      { id: "TUN-VALERY",       name: "Y. Valery",         position: "RB",  role: "starter" },
      { id: "TUN-SASSI",        name: "F. Sassi",          position: "CDM", role: "starter" },
      { id: "TUN-SKHIRI",       name: "E. Skhiri",         position: "CDM", role: "starter" },
      { id: "TUN-MEJBRI",       name: "H. Mejbri",         position: "LM",  role: "starter" },
      { id: "TUN-MAHMOUD",      name: "M. H. Mahmoud",     position: "CAM", role: "starter" },
      { id: "TUN-GHARBI",       name: "I. Gharbi",         position: "RM",  role: "starter" },
      { id: "TUN-MASTOURI",     name: "H. Mastouri",       position: "ST",  role: "starter" },

      // Запасные
      { id: "TUN-MERIAH",       name: "Y. Meriah",         position: "CB",  role: "bench" },
      { id: "TUN-ACHOURI",      name: "E. Achouri",        position: "CAM", role: "bench" },
      { id: "TUN-CHAOUAT",      name: "F. Chaouat",        position: "ST",  role: "bench" },
      { id: "TUN-SAAD",         name: "E. Saad",           position: "RM",  role: "bench" },
      { id: "TUN-ROMDHANE",     name: "M. Ali Ben Romdhane", position: "LM", role: "bench" },
      { id: "TUN-BEN-ALI",      name: "M. Ben Ali",        position: "RB",  role: "bench" },
      { id: "TUN-BEN-SAID",     name: "B. Ben Said",       position: "GK",  role: "bench" },
      { id: "TUN-FARHATI",      name: "N. Farhati",        position: "GK",  role: "bench" },
      { id: "TUN-AROUS",        name: "A. Arous",          position: "LB",  role: "bench" },
      { id: "TUN-GHANDRI",      name: "N. Ghandri",        position: "CB",  role: "bench" },
      { id: "TUN-MAALOUL",      name: "A. Maaloul",        position: "CB",  role: "bench" },
      { id: "TUN-SLITI",        name: "N. Sliti",          position: "LM",  role: "bench" },
      { id: "TUN-BEN-OUANES",   name: "M. Ben Ouanes",     position: "LM",  role: "bench" },
      { id: "TUN-TOUNEKTI",     name: "S. Tounekti",       position: "LM",  role: "bench" },
      { id: "TUN-JAZIRI",       name: "S. Jaziri",         position: "ST",  role: "bench" },
    ],
  },

  BEL: {
    formation: "4-3-3",
    players: [
      // Основной состав
      { id: "BEL-LAMMENS",       name: "S. Lammens",          position: "GK",  role: "starter" },
      { id: "BEL-CASTAGNE",      name: "T. Castagne",         position: "LB",  role: "starter" },
      { id: "BEL-THEATE",        name: "A. Theate",           position: "CB",  role: "starter" },
      { id: "BEL-MECHELE",       name: "B. Mechele",          position: "CB",  role: "starter" },
      { id: "BEL-MEUNIER",       name: "T. Meunier",          position: "RB",  role: "starter" },
      { id: "BEL-VANAKEN",       name: "H. Vanaken",          position: "CM",  role: "starter" },
      { id: "BEL-DE-BRUYNE",     name: "K. De Bruyne",        position: "CM",  role: "starter" },
      { id: "BEL-TIELEMANS",     name: "Y. Tielemans",        position: "CM",  role: "starter" },
      { id: "BEL-DOKU",          name: "J. Doku",             position: "LW",  role: "starter" },
      { id: "BEL-DE-KETELAERE",  name: "C. De Ketelaere",     position: "ST",  role: "starter" },
      { id: "BEL-SAELEMAEKERS",  name: "A. Saelemaekers",     position: "RW",  role: "starter" },

      // Запасные
      { id: "BEL-RASKIN",        name: "N. Raskin",           position: "CM",  role: "bench" },
      { id: "BEL-WITSEL",        name: "A. Witsel",           position: "CM",  role: "bench" },
      { id: "BEL-TROSSARD",      name: "L. Trossard",         position: "RW",  role: "bench" },
      { id: "BEL-OPENDA",        name: "L. Openda",           position: "ST",  role: "bench" },
      { id: "BEL-LUKEBAKIO",     name: "D. Lukebakio",        position: "LW",  role: "bench" },
      { id: "BEL-MOREIRA",       name: "D. Moreira",          position: "CM",  role: "bench" },
      { id: "BEL-PENDERS",       name: "M. Penders",          position: "GK",  role: "bench" },
      { id: "BEL-SELS",          name: "M. Sels",             position: "GK",  role: "bench" },
      { id: "BEL-DE-CUYPER",     name: "M. De Cuyper",        position: "LB",  role: "bench" },
      { id: "BEL-DE-WINTER",     name: "K. De Winter",        position: "CB",  role: "bench" },
      { id: "BEL-SEYS",          name: "J. Seys",             position: "LB",  role: "bench" },
      { id: "BEL-VANHOUTTE",     name: "C. Vanhoutte",        position: "CM",  role: "bench" },
      { id: "BEL-VERMANT",       name: "R. Vermant",          position: "ST",  role: "bench" },
    ],
  },

  EGY: {
    formation: "4-2-3-1",
    players: [
      // Основной состав
      { id: "EGY-SHOBEIR",       name: "M. Shobeir",          position: "GK",  role: "starter" },
      { id: "EGY-SOBHI",         name: "K. Sobhi",            position: "LB",  role: "starter" },
      { id: "EGY-RABIA",         name: "R. Rabia",            position: "CB",  role: "starter" },
      { id: "EGY-H-FATHY",       name: "H. Fathy",            position: "CB",  role: "starter" },
      { id: "EGY-HANY",          name: "M. Hany",             position: "RB",  role: "starter" },
      { id: "EGY-LASHEEN",       name: "M. Lasheen",          position: "CDM", role: "starter" },
      { id: "EGY-ZIZO",          name: "Zizo",                position: "CDM", role: "starter" },
      { id: "EGY-TREZEGUET",     name: "M. Trezeguet",        position: "LM",  role: "starter" },
      { id: "EGY-ASHOUR",        name: "E. Ashour",           position: "CAM", role: "starter" },
      { id: "EGY-SALAH",         name: "M. Salah",            position: "RM",  role: "starter" },
      { id: "EGY-MARMOUSH",      name: "O. Marmoush",         position: "ST",  role: "starter" },

      // Запасные
      { id: "EGY-SABER",         name: "M. Saber",            position: "LM",  role: "bench" },
      { id: "EGY-M-MOHAMED",     name: "M. Mohamed",          position: "ST",  role: "bench" },
      { id: "EGY-I-ADEL",        name: "I. Adel",             position: "ST",  role: "bench" },
      { id: "EGY-M-SABHI",       name: "M. Sabhi",            position: "GK",  role: "bench" },
      { id: "EGY-EL-SHENAWY-A",  name: "A. El-Shenawy",       position: "GK",  role: "bench" },
      { id: "EGY-EL-SHENAWY-M",  name: "M. El-Shenawy",       position: "GK",  role: "bench" },
      { id: "EGY-EID",           name: "A. Eid",              position: "RB",  role: "bench" },
      { id: "EGY-ISMAIL",        name: "M. Ismail",           position: "CB",  role: "bench" },
      { id: "EGY-M-FATHY",       name: "M. Fathy",            position: "CDM", role: "bench" },
      { id: "EGY-SHEHATA",       name: "M. Shehata",          position: "CDM", role: "bench" },
      { id: "EGY-FAISAL",        name: "O. Faisal",           position: "LM",  role: "bench" },
    ],
  },

  IRN: {
    formation: "4-2-3-1",
    players: [
      // Основной состав
      { id: "IRN-BEIRANVAND",    name: "A. Beiranvand",       position: "GK",  role: "starter" },
      { id: "IRN-GHODDOS",       name: "S. Ghoddos",          position: "LB",  role: "starter" },
      { id: "IRN-EZATOLAHI",     name: "S. Ezatolahi",        position: "CB",  role: "starter" },
      { id: "IRN-MOHAMMADI",     name: "M. Mohammadi",        position: "CB",  role: "starter" },
      { id: "IRN-KHALILZADEH",   name: "S. Khalilzadeh",      position: "RB",  role: "starter" },
      { id: "IRN-HARDANI",       name: "S. Hardani",          position: "CDM", role: "starter" },
      { id: "IRN-HASHEMNEJAD",   name: "M. Hashemnejad",      position: "CDM", role: "starter" },
      { id: "IRN-HOSSEINI-M",    name: "M. Hosseini",         position: "LM",  role: "starter" },
      { id: "IRN-TAREMI",        name: "M. Taremi",           position: "CAM", role: "starter" },
      { id: "IRN-ALIPOURGHARA",  name: "A. Alipourghara",     position: "RM",  role: "starter" },
      { id: "IRN-HOSSEINZADEH",  name: "A. Hosseinzadeh",     position: "ST",  role: "starter" },

      // Запасные
      { id: "IRN-GHORBANI",      name: "M. Ghorbani",         position: "CB",  role: "bench" },
      { id: "IRN-NOORAFKAN",     name: "O. Noorafkan",        position: "CDM", role: "bench" },
      { id: "IRN-KOUSHKI",       name: "A. Koushki",          position: "LB",  role: "bench" },
      { id: "IRN-MOHEBI",        name: "M. Mohebi",           position: "ST",  role: "bench" },
      { id: "IRN-YOUSEFI",       name: "A. Yousefi",          position: "CDM", role: "bench" },
      { id: "IRN-HOSSEINI-S",    name: "S. Hosseini",         position: "GK",  role: "bench" },
      { id: "IRN-NIAZMAND",      name: "P. Niazmand",         position: "GK",  role: "bench" },
      { id: "IRN-AKHBARI",       name: "M. Akhbari",          position: "GK",  role: "bench" },
      { id: "IRN-ESMAEILIFAR",   name: "D. Esmaeilifar",      position: "RB",  role: "bench" },
      { id: "IRN-NEMATI",        name: "A. Nemati",           position: "CB",  role: "bench" },
      { id: "IRN-KANAANI",       name: "H. Kanaani",          position: "CB",  role: "bench" },
      { id: "IRN-HABIBINEJAD",   name: "H. Habibinejad",      position: "CAM", role: "bench" },
      { id: "IRN-TIKDARI",       name: "M. Tikdari",          position: "ST",  role: "bench" },
    ],
  },

  NZL: {
    formation: "4-2-3-1",
    players: [
      // Основной состав
      { id: "NZL-CROCOMBE",      name: "M. Crocombe",        position: "GK",  role: "starter" },
      { id: "NZL-DE-VRIES",      name: "F. D. Vries",        position: "LB",  role: "starter" },
      { id: "NZL-BINDON",        name: "T. Bindon",          position: "CB",  role: "starter" },
      { id: "NZL-SURMAN",        name: "F. Surman",          position: "CB",  role: "starter" },
      { id: "NZL-TUILOMA",       name: "B. Tuiloma",         position: "RB",  role: "starter" },
      { id: "NZL-RUFER",         name: "A. Rufer",           position: "CDM", role: "starter" },
      { id: "NZL-STAMENIC",      name: "M. Stamenic",        position: "CDM", role: "starter" },
      { id: "NZL-OLD",           name: "B. Old",             position: "LM",  role: "starter" },
      { id: "NZL-SINGH",         name: "S. Singh",           position: "CAM", role: "starter" },
      { id: "NZL-JUST",          name: "E. Just",            position: "RM",  role: "starter" },
      { id: "NZL-WAINE",         name: "B. Waine",           position: "ST",  role: "starter" },

      // Запасные
      { id: "NZL-ROUX",          name: "S. Roux",            position: "RB",  role: "bench" },
      { id: "NZL-GARBETT",       name: "M. Garbett",         position: "RM",  role: "bench" },
      { id: "NZL-BARBAROUSES",   name: "K. Barbarouses",     position: "LM",  role: "bench" },
      { id: "NZL-MCGARRY",       name: "J. McGarry",         position: "LB",  role: "bench" },
      { id: "NZL-PARKER-PRICE",  name: "O. Parker Price",    position: "CDM", role: "bench" },
      { id: "NZL-RANDALL",       name: "J. Randall",         position: "ST",  role: "bench" },
      { id: "NZL-SIMS",          name: "K. Sims",            position: "GK",  role: "bench" },
      { id: "NZL-TZANEV",        name: "N. Tzanev",          position: "GK",  role: "bench" },
      { id: "NZL-BOXALL",        name: "M. Boxall",          position: "CB",  role: "bench" },
      { id: "NZL-SMITH",         name: "T. Smith",           position: "CB",  role: "bench" },
      { id: "NZL-STANGER",       name: "G. Stanger",         position: "CB",  role: "bench" },
      { id: "NZL-BELL",          name: "J. Bell",            position: "CDM", role: "bench" },
      { id: "NZL-DE-JONG",       name: "A. de Jong",         position: "CAM", role: "bench" },
    ],
  },

  // Остальные сборные добавим позже тем же форматом
};

